In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])
print(a)
print(type(a))

[0 1 2 3]
<class 'numpy.ndarray'>


In [4]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
L = range(1000)
%timeit [i**2 for i in L]

264 µs ± 6.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

1.42 µs ± 19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Creating numpy array

In [9]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [10]:
# Dimensions
a.ndim

1

In [11]:
# Shape
a.shape

(4,)

In [12]:
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]])
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# Dimension
b.ndim

2

In [17]:
# Shape
b.shape

(3, 3)

In [24]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
c.ndim

3

In [26]:
c.shape

(2, 2, 2)

**n Dimensional array is called a tensor**

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Generate numpy array within range 1 to 10 with 2 as step size interval.
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [33]:
# Dividing the interval into 6 points with 0 to 1 range.
c = np.linspace(0, 1, 6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [40]:
# Creating a matrix on ones.
a = np.ones((3, 3))
print(a)
print(a.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)


In [46]:
# Creating a 3-D matrix of zeros.
a = np.zeros((2, 2, 2))
print(a)
print(a.ndim)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [52]:
# Creating a Identity matrix.
a = np.eye(3, 3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])