In [1]:
import numpy as np

### Scalar Operations on Array

In [6]:
# Scalar addition of array.
a = np.array([1, 2, 3, 4])
a = a + 1
print(a)

[2 3 4 5]


### Element wise operation on array.

In [8]:
a = np.array([1, 2, 3, 4])
a = a**2
print(a)

[ 1  4  9 16]


In [9]:
b = np.ones(4) + 1
print(b)

[2. 2. 2. 2.]


In [10]:
a - b

array([-1.,  2.,  7., 14.])

In [11]:
a * b

array([ 2.,  8., 18., 32.])

### Matrix Multiplication

In [12]:
c = np.diag([1, 2, 3, 4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
# 1st method of Matrix multiplication.
c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [16]:
# 2nd method Matrix multiplication.
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])